#!/bin/bash
set -o nounset -o errexit -o pipefail


#install code-server  
cd /opt && \
  mkdir /opt/code-server && \
  cd /opt/code-server && \
  wget -qO- https://github.com/codercom/code-server/releases/download/1.868-vsc1.33.1/code-server1.868-vsc1.33.1-linux-x64.tar.gz | tar zxvf - --strip-components=1

#install the python extension for vs-code
apt-get install -y bsdtar
mkdir -p /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2019.3.6558 && \
cd /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2019.3.6558
 curl -JL https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2019.3.6558/vspackage | bsdtar -xvf - extension
  mv extension /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2019.3.6558

mv /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2019.3.6558/extension /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2019.3.6558
chown ubuntu:ubuntu /home/ubuntu/.local/share/code-server/


export PATH=/opt/code-server:$PATH

#echo export PATH=/opt/code-server:$PATH >> /home/ubuntu/.domino-defaults

pip install git+git://github.com/ChuckRIHead/jupyter_codeserver_proxy-.git

