#!/bin/bash
set -o nounset -o errexit -o pipefail

#Jupyterlab is pinned since there a compatibility issue with nbserverproxy and jupyter-server-proxy
pip install --upgrade six && pip install jupyterlab==0.35.4 && pip install --upgrade jupyter
