#!/bin/bash
set -o nounset -o errexit -o pipefail

IP_ADDR=$(cat /etc/hostname)
CONF_DIR="$HOME/.jupyter"
CONF_FILE="${CONF_DIR}/jupyter_notebook_config.py"

PREFIX=/${DOMINO_PROJECT_OWNER}/${DOMINO_PROJECT_NAME}/notebookSession/${DOMINO_RUN_ID}/

mkdir -p "${CONF_DIR}"

cat <<EOF >>"${CONF_FILE}"
c.NotebookApp.notebook_dir = '/'
c.NotebookApp.base_url = '${PREFIX}'
c.NotebookApp.tornado_settings = {'headers': {'Content-Security-Policy': 'frame-ancestors *'}}
c.NotebookApp.default_url = 'tree${DOMINO_WORKING_DIR}'
#disable quit button in Jupyter 5.5+
c.NotebookApp.quit_button = False
c.NotebookApp.disable_check_xsrf = True
EOF

# Replace * in "--ip=*" with the actual IP address of the container
COMMAND='jupyter notebook --no-browser --ip=0.0.0.0 2>&1'
FINAL_COMMAND=$(echo "${COMMAND}" | sed "s/--ip=\\*/--ip=${IP_ADDR}/")

eval ${FINAL_COMMAND}
