#!/bin/bash
set -o nounset -o errexit -o pipefail

IP_ADDR=$(cat /etc/hostname)
CONF_DIR="$HOME/.ipython"
CONF_FILE="${CONF_DIR}/ipython_config.py"

mkdir -p "${CONF_DIR}"

cat <<EOF >>"${CONF_FILE}"
c.NotebookApp.notebook_dir = '/'
c.NotebookApp.tornado_settings = {'headers': {'Content-Security-Policy': 'frame-ancestors *'}}
c.NotebookApp.default_url = 'tree${DOMINO_WORKING_DIR}'

EOF

# Replace * in "--ip=*" with the actual IP address of the container
COMMAND='jupyter notebook --no-browser --ip=* 2>&1'
FINAL_COMMAND=$(echo "${COMMAND}" | sed "s/--ip=\\*/--ip=${IP_ADDR}/")

eval ${FINAL_COMMAND}
