#!/bin/bash
set -o nounset -o errexit -o pipefail


#install code-server  
cd /opt && \
  mkdir /opt/code-server && \
  cd /opt/code-server && \
  wget -qO- https://github.com/cdr/code-server/releases/download/3.2.0/code-server-3.2.0-linux-x86_64.tar.gz | tar zxvf - --strip-components=1


#install the python extension for vs-code
apt-get update -y
apt-get install -y bsdtar
mkdir -p /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.4.74986 && \
cd /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.4.74986
curl -JL https://github.com/microsoft/vscode-python/releases/download/2020.4.74986/ms-python-release.vsix | bsdtar -xvf - extension

cd /home/ubuntu/.local/share/code-server/extensions/ms-python.python-2020.4.74986/extension/ && mv * ../


chown -R ubuntu:ubuntu /home/ubuntu/.local/share/code-server/


export PATH=/opt/code-server:$PATH

echo 'export PATH=/opt/code-server:$PATH' >> /home/ubuntu/.domino-defaults

rm -rf /var/lib/apt/lists/*
