#!/bin/bash
set -o nounset -o errexit -o pipefail


 yum install -y -q https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.2.5033-x86_64.rpm


 ln -s /usr/lib/rstudio-server /usr/local/lib/rstudio-server 
 chown -R root:root /usr/lib/rstudio-server

 echo "www-frame-origin=any" >> /etc/rstudio/rserver.conf
chown domino:domino /etc/rstudio/rserver.conf

#Make rmarkdown::render work outside of rstudio. https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin
ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc /usr/local/bin
