#!/bin/bash
set -o nounset -o errexit -o pipefail

#Configure Spark if present
if [ -n "${SPARK_HOME:-}" ]; then
  echo ".libPaths(c(file.path(Sys.getenv('SPARK_HOME'), 'R', 'lib'), .libPaths()))" >> ~/.Rprofile
fi

# Set environment variable for where the history file will be stored
export R_HISTFILE='domino.Rhistory'

printenv >> ~/.Renviron

# Set initial working directory, which is the diretory RStudio opens up to
mkdir -p ~/.rstudio/monitored/user-settings/
echo -e "initialWorkingDirectory=\"${DRT_WORKING_DIR:-"${DOMINO_WORKING_DIR}"}\"\n" >> ~/.rstudio/monitored/user-settings/user-settings

# According to RStudio documentation, to enable opening RStudio in an iframe (or any frame), we need to set `www-frame-origin` config parameter to the allowed host and port.
# But the tests show that we are able to open RStudio in the Domino iframe regardless of the value of this param, as long as the param is present.
# So we set it for now to "any", allowing RStudio to be embedded in any frame. --dvolk
echo "www-frame-origin=any" >> /etc/rstudio/rserver.conf

/usr/lib/rstudio-server/bin/rserver --www-port=8888 --auth-none=1 --server-app-armor-enabled=0
