#!/bin/bash
set -o nounset -o errexit -o pipefail

# Update package lists and install dependencies
apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Install ttyd
curl -sL "https://github.com/tsl0922/ttyd/releases/download/1.6.3/ttyd.x86_64" -o /usr/local/bin/ttyd
chmod +x /usr/local/bin/ttyd
